# Generated by Django 3.0.4 on 2020-05-27 05:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_on', models.DateTimeField(default=datetime.datetime(2020, 5, 28, 5, 55, 35, 144616, tzinfo=utc))),
                ('currently_active', models.BooleanField(default=True)),
                ('pdf', models.FileField(upload_to='assignments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TeacherProfile')),
            ],
        ),
    ]
