# Generated by Django 3.0.4 on 2020-05-30 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 10, 9, 36, 363775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pdf',
            field=models.FileField(default='sample.pdf', upload_to='assignments'),
        ),
    ]
