# Generated by Django 3.0.4 on 2020-06-06 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20200606_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 14, 46, 59, 471523, tzinfo=utc)),
        ),
    ]
