# Generated by Django 3.0.4 on 2020-06-06 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20200606_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 14, 50, 30, 162141, tzinfo=utc)),
        ),
    ]
