# Generated by Django 3.0.4 on 2020-06-07 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20200607_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 12, 49, 30, 975500, tzinfo=utc)),
        ),
    ]
