# Generated by Django 3.0.4 on 2020-06-25 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20200608_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 5, 30, 573727, tzinfo=utc)),
        ),
    ]
