# Generated by Django 3.0.4 on 2020-06-27 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20200625_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 12, 37, 31, 720742, tzinfo=utc)),
        ),
    ]
