# Generated by Django 3.0.4 on 2020-06-27 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20200627_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 12, 47, 21, 660875, tzinfo=utc)),
        ),
    ]
