# Generated by Django 3.0.4 on 2020-06-27 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_auto_20200627_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 13, 11, 20, 486320, tzinfo=utc)),
        ),
    ]
