# Generated by Django 3.0.4 on 2020-07-02 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_auto_20200627_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 11, 47, 27, 154486, tzinfo=utc)),
        ),
    ]
