# Generated by Django 3.0.4 on 2020-07-02 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_auto_20200702_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 11, 56, 30, 978596, tzinfo=utc)),
        ),
    ]
