# Generated by Django 3.0.4 on 2020-05-27 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='teacher_profile_pics')),
                ('qualification', models.CharField(default=None, max_length=255, null=True)),
                ('assigned_course', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='student_profile_pics')),
                ('year', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=60)),
                ('assignments_accepted', models.IntegerField(default=0)),
                ('is_current_student', models.BooleanField(default=True)),
                ('course', models.CharField(default=None, max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
