# Generated by Django 3.0.4 on 2020-06-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_studentprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
