# Generated by Django 3.0.4 on 2020-06-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assignments_rejected',
            field=models.IntegerField(default=0),
        ),
    ]
