# Generated by Django 3.0.4 on 2020-07-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_assignments_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='marks',
        ),
    ]
