# Generated by Django 3.0.4 on 2020-05-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course', models.CharField(default=None, max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='answers')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StudentProfile')),
            ],
        ),
    ]
