# Generated by Django 3.0.4 on 2020-06-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200606_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pdf',
            field=models.FileField(default='sample.pdf', upload_to='answers'),
        ),
    ]
