# Generated by Django 3.0.4 on 2020-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20200608_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(default='Not Reviewed', max_length=20),
        ),
    ]
