# Generated by Django 3.0.4 on 2020-06-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
